swagger: '2.0'
info:
  description: Hakim's IPMI Pollers and IBMS CRUD
  version: 1.0.0
  title: STI2017
  # put the contact info for your development or API team
  contact:
    email: 1502314F@student.tp.edu.sg

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /ipmipollers/read:
    get:
      tags:
      - IPMI CRUD
      summary: Read a list of pollers
      operationId: readipmipollers
      description: |
        Get a list of pollers by passing the authentication token
      produces:
      - application/json
      parameters:
      - in: header
        name: Content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: Token
        description: to validate authentication
        type: string
      responses:
        200:
          description: List of pollers retrieved
        400:
          description: bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Serval Error
          
  /ipmipollers/create:
    post:
      tags:
      - IPMI CRUD
      summary: Create a New IPMI Poller
      operationId: createipmipollers
      description: |
        Creates a new IPMI Poller
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Data
        description: IPMI Poller data
        schema:
          $ref: '#/definitions/ipmipollers_create'
      - in: header
        name: Content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string  
      - in: header
        name: Token
        description: to validate authentication
        required: true
        type: string
      responses:
        200:
          description: IPMI Poller Created
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500: 
          description: Internal Server Error
         
         
  /ipmipollers/update:
    patch:
      tags: 
      - IPMI CRUD
      summary: Update a Single IPMI Poller
      operationId: updateipmipollers
      description: |
        Updates a single IPMI Poller
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: Input Poller ID
        description: IPMI Poller Id to update
        required: true
        type: string
      - in: body
        name: Data
        description: IPMI Poller data to update
        schema:
          $ref: '#/definitions/ipmipollers_update'
      - in: header
        name: Content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: Token
        description: to validate authentication
        required: true
        type: string    
      responses:
        200:
          description: IPMI Poller Updated
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /ipmipollers/delete:
    delete:
      tags: 
      - IPMI CRUD
      summary: Delete a Single IPMI Poller
      operationId: deleteipmipollers
      description: |
        Deletes a single IPMI Poller
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Data
        description: IPMI Poller id to delete
        required: true
        schema:
          $ref: '#/definitions/ipmipollers_delete'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string    
      responses:
        200:
          description: IPMI Poller Deleted
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /ibms/create:
    put:
      tags:
      - IBMS management
      summary: Create a node-based IBMS on RackHD
      operationId: createibms
      description: |
        Create a new node-based IBMS on RackHD
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Data
        description: Send Data
        schema:
         $ref: '#/definitions/ibms_create'
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string
      responses:
        200:
          description: Successful creation of IBMS node
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error
          
  /ibms/read:
    get:
      tags:
      - IBMS management
      summary: List all of the IBMS Settings
      operationId: readibms
      description: |
        Shows all ibms on RackHD
      produces:
      - application/json
      parameters:
      - in: header
        name: content-type
        description: |
          show information about ibms nodes
        required: true
        type: string
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string
        
      responses:
        200:
          description: Successful display of IBMS node
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error
          
  /ibms/update:
    patch:
      tags:
      - IBMS management
      summary: Update an IBMS Management Setting
      operationId: updateibms
      description: Update IBMS
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: data
        schema:
          $ref: '#/definitions/ibms_update'
      - in: header
        name: token
        description: Pass a token to validate authentication
        required: true
        type: string
      responses:
        200:
          description: Successful update of IBMS node
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error

  /ibms/delete:
    delete:
      tags:
      - IBMS management
      summary: Delete ibms settings based on its NodeID
      operationId: operation
      description: |
        delete an ibms on RackHD
      produces:
      - application/json
      parameters:
      - in: body
        name: Data
        description: nodeID
        schema:
            $ref: '#/definitions/ibms_delete'
      - in: header
        name: content-type
        description: Indicate media type of resource e.g. application/json
        required: true
        type: string
      - name: token
        in: header
        description: Pass a token to validate authentication
        required: true
        type: string
      responses:
        200:
          description: IBMS Delete Success
        400:
          description: Bad input parameter
        405:
          description: Method not allowed
        404:
          description: Not found
        500:
          description: Internal Server Error
          
definitions:
  ipmipollers_create:
    type: object
    required:
    - type
    - pollInterval
    - node
    - command
    properties:
      type:
        type: string
        format: string
        example: ipmi
      pollInterval:
        type: string
        format: string
        example: 10000
      node:
        type: string
        format: UUID
        example: 54daadd764f1a8f1088fdc42
      command:
        type: string
        format: string
        example: power
  
  ipmipollers_update:
    type: object
    required:
    - pid
    - type
    - pollInterval
    - node
    - command
    properties:
     pid:
      type: string
      format: UUID
      example: 59495d5004a9f71405c06eec
     type:
      type: string
      format: string
      example: ipmi
     pollInterval:
      type: string
      format: string
      example: 10000
     node:
      type: string
      format: UUID
      example: 54daadd764f1a8f1088fdc42
     command: 
      type: string
      format: string
      example: power
      
  ipmipollers_delete:
   type: object
   required:
    - pid
   properties:
    pid:
     type: string
     format: UUID
     example: 59495d5004a9f71405c06eec
     
  ibms_create:
   type: object
   required:
   - nodeId
   - service
   - community
   - host
   properties:
      nodeId:
        type: string
        format: string
        example: 590cbcbf29ba9e40471c9f3c
      service:
        type: string
        format: string
        example: snmp-ibm-service
      community:
        type: string
        format: string
        example: public
      host:
        type: string
        format: string
        example: 192.171.5.1
 
  ibms_update:
    type: object
    required:
    - nodeId
    - service
    - community
    - host
    properties:
      nodeId:
        type: string
        format: string
        example: 590cbcbf29ba9e40471c9f3c
      service:
        type: string
        format: string
        example: snmp-ibm-service
      community:
        type: string
        format: string
        example: public
      host:
        type: string
        format: string
        example: 192.171.5.1
  
  ibms_delete:
    type: object
    required:
    - nodeId
    properties:
     nodeId: 
      type: string
      format: uuid
      example: 590cbcbf29ba9e40471c9f3c
     
     
      
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
# basePath: /rackhd/
# host: localhost:5000
schemes:
 - https
# basePath: /rackhd/
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /HakimRazalee/app/1.0.0
